### ISSUE TITLE
Smoketest failures after 2018_07 import

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#1065]
```
call_command ('run_smoketests', '2018_07')
.........F.F
======================================================================
FAIL: test_chemical_by_one_practice (pipeline.smoketests.TestSmokeTestSpendingByOnePractice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/webapps/openprescribing/openprescribing/pipeline/smoketests.py", line 98, in test_chemical_by_one_practice
    params
  File "/webapps/openprescribing/openprescribing/pipeline/smoketests.py", line 40, in _run_tests
    self.assertEqual(len(all_rows), PRESCRIBING_DATA_MONTHS)
AssertionError: 58 != 60

======================================================================
FAIL: test_presentation_by_one_practice (pipeline.smoketests.TestSmokeTestSpendingByOnePractice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/webapps/openprescribing/openprescribing/pipeline/smoketests.py", line 90, in test_presentation_by_one_practice
    params
  File "/webapps/openprescribing/openprescribing/pipeline/smoketests.py", line 40, in _run_tests
    self.assertEqual(len(all_rows), PRESCRIBING_DATA_MONTHS)
AssertionError: 58 != 60

----------------------------------------------------------------------
Ran 12 tests in 5.407s

FAILED (failures=2)
```

**Comment by inglesp** [comment]
These failures suggest that the API is only returning 58 months of data when we expect 60 months.  (60 == 12 * 5, ie five years.)

The tests are making requests to the following end points:

* https://openprescribing.net/api/1.0/spending_by_practice/?format=json&code=0212000AA&org=A81015
* https://openprescribing.net/api/1.0/spending_by_practice/?format=json&code=0703021Q0BBAAAA&org=A81015

For both endpoints we're getting 58 records, for dates between 2013_08 and 2018_05 (inclusive):

```
>>> rsp = requests.get('https://openprescribing.net/api/1.0/spending_by_practice/?format=json&code=0212000AA&org=A81015')
>>> rr = rsp.json()
>>> len(rr)
58
>>> min(r['date'] for r in rr)
'2013-08-01'
>>> max(r['date'] for r in rr)
'2018-05-01'
```

The [practice in question](https://openprescribing.net/practice/A81015/) has prescribed nothing for `0212000AA` or `0703021Q0BBAAAA` in 2018_06 or 2018_07:

```
>>> Prescription.objects.filter(practice=p, processing_date__in=['2018-06-01', '2018-07-01'], presentation_code__startswith='0212000AA').count()
0
>>> Prescription.objects.filter(practice=p, processing_date__in=['2018-06-01', '2018-07-01'], presentation_code__startswith='0703021Q0BBAAAA').count()
0
```

The practice hasn't closed:

```
>>> Practice.objects.get(pk='A81015').close_date is None
True
```

But the practice has prescribed significantly less in 2018_06 and 2018_07:

```
>>> for month in '34567':
...   date = '2018-0{}-01'.format(month)
...   print date, Prescription.objects.filter(practice=p, processing_date=date).count()
... 
2018-03-01 901
2018-04-01 925
2018-05-01 497
2018-06-01 95
2018-07-01 42
```

Which suggests it may be in the process of closing.

And yes, it's dormant:

```
>>> Practice.objects.get(pk='A81015').status_code
u'D'
```
