### ISSUE TITLE
Possible non-deterministic test failure

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1141]
```
======================================================================
ERROR: test_existing_files_deleted (frontend.tests.commands.test_create_views.CommandsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/openprescribing/frontend/tests/commands/test_create_views.py", line 130, in test_existing_files_deleted
    call_command('create_views')
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/code/openprescribing/frontend/management/commands/create_views.py", line 61, in handle
    self.fill_views()
  File "/code/openprescribing/frontend/management/commands/create_views.py", line 92, in fill_views
    self.download_and_import(table)
  File "/code/openprescribing/frontend/management/commands/create_views.py", line 120, in download_and_import
    cmd = generate_sort_cmd(table_id, field_names, raw_path, sorted_path)
  File "/code/openprescribing/frontend/management/commands/create_views.py", line 181, in generate_sort_cmd
    sort_key_ixs = [field_names.index(k) + 1 for k in sort_keys]
ValueError: 'chemical_id' is not in list
----------------------------------------------------------------------
```

**Comment by sebbacon** [comment]
Confirmed that this went away on re-running the tests (in Travis)

**Comment by evansd** [comment]
Can also confirm that this has reoccurred a few times and then gone away on rerunning the Travis job

**Comment by inglesp** [comment]
We can close this now that `create_views` is no longer run.
