### ISSUE TITLE
Non-deterministic race condition seen in test run

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1233]
```
======================================================================
ERROR: test_total_spending_by_code (frontend.tests.test_api_spending.TestSpending)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/openprescribing/frontend/tests/test_api_spending.py", line 165, in test_total_spending_by_code
    _create_prescribing_tables()
  File "/code/openprescribing/frontend/tests/test_api_spending.py", line 20, in _create_prescribing_tables
    cursor.execute(cmd % (table_name, table_name))
  File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
OperationalError: deadlock detected
DETAIL:  Process 310 waits for ShareUpdateExclusiveLock on relation 22556 of database 20626; blocked by process 308.
Process 308 waits for AccessShareLock on relation 43566 of database 20626; blocked by process 310.
HINT:  See server log for query details.
```

**Comment by HelenCEBM** [comment]
Any action on this @sebbacon ?

**Comment by sebbacon** [comment]
No but let's leave open for 3 months and close if no more by then.

**Comment by evansd** [comment]
It's been more than 3 months.
