### ISSUE TITLE
Send final email to unconfirmed subscribers

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#1427]
Once #1426 is merged (i.e. the wording for the email we're about to send) we need to send a final message to all unconfirmed subscribers.

First, check that the template override thing is working correctly:
```
./manage.py diffsettings --settings=openprescribing.settings.templateoverride | grep TEMPLATE
```
The path `template_overrides` should be in the list of template directories.

Then send emails to just me using:
```
./manage.py resend_confirmation_emails --settings=openprescribing.settings.templateoverride --email_contains drhevans --sent_log=emails_sent.txt
```

Assuming that all looks good, send the whole lot with:
```
./manage.py resend_confirmation_emails --settings=openprescribing.settings.templateoverride --email_contains=@ --sent_log=emails_sent.txt
```

**Comment by evansd** [comment]
This blew up when it hit an invalid email address. I'm including the list of addresses it already sent to as we'll need to make sure we don't resend when we fix this:
```
Resending to phil.evans|@nhs.net
Resending to iomerji@hotmail.com
Resending to mohamma.tahir3@nhs.net
Resending to lois.taylor3@nhs.net
Resending to n.dhatariya@nhs.net
Resending to mcgarr901@msn.com
Resending to jamescave@outlook.com
Resending to Nathan.bird@gp-c84055.nhs.uk
Resending to chadlee.simpson@hotmail.com
Resending to jagadish.s@bbukltd.com
Resending to rebecca.richardson18@nhs.net
Resending to Kate.holder@bayer.com
Resending to nicola.bruce@gp-l81047.nhs.nt
Traceback (most recent call last):
  File "./manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/resend_confirmation_emails.py", line 35, in handle
    send_email_confirmation(request, user)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/allauth/account/utils.py", line 314, in send_email_confirmation
    signup=signup)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/allauth/account/models.py", line 60, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/allauth/account/models.py", line 166, in send
    get_adapter(request).send_confirmation_mail(request, self, signup)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/allauth/account/adapter.py", line 450, in send_confirmation_mail
    ctx)
  File "/webapps/openprescribing/openprescribing/frontend/account/adapter.py", line 20, in send_mail
    msg.send()
  File "/webapps/openprescribing/openprescribing/frontend/models.py", line 809, in send
    self.message.send()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/mail/message.py", line 348, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/anymail/backends/base.py", line 95, in send_messages
    sent = self._send(message)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/anymail/backends/base_requests.py", line 60, in _send
    return super(AnymailRequestsBackend, self)._send(message)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/anymail/backends/base.py", line 125, in _send
    response = self.post_to_esp(payload, message)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/anymail/backends/base_requests.py", line 82, in post_to_esp
    self.raise_for_status(response, payload, message)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/anymail/backends/base_requests.py", line 94, in raise_for_status
    backend=self)
anymail.exceptions.AnymailRequestsAPIError: Sending a message to nicola.bruce@gp-l81047.nhs.nt from OpenPrescribing <feedback@openprescribing.net>
Mailgun API response 400: BAD REQUEST
{
  "message": "'to' parameter is not a valid address. please check documentation"
}
```
