### ISSUE TITLE
Tests are failing on fresh install

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#15]

**Comment by sebbacon** [comment]
@annapowellsmith, here's the errors

```
======================================================================
ERROR: setUpModule (frontend.tests.test_api_measures)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/openprescribing/frontend/tests/test_api_measures.py", line 57, in setUpModule
    management.call_command('import_hscic_prescribing', *args, **new_opts)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/code/openprescribing/frontend/management/commands/import_hscic_prescribing.py", line 55, in handle
    self.import_shas_and_pcts(f)
  File "/code/openprescribing/frontend/management/commands/import_hscic_prescribing.py", line 67, in import_shas_and_pcts
    rows = csv.reader(open(filename, 'rU'))
IOError: [Errno 2] No such file or directory: 'frontend/tests/fixtures/commands/T201509PDPI+BNFT_formatted.CSV'
```

```
======================================================================
ERROR: setUpModule (frontend.tests.commands.test_import_measures)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/openprescribing/frontend/tests/commands/test_import_measures.py", line 57, in setUpModule
    call_command('import_hscic_prescribing', *args, **new_opts)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/code/openprescribing/frontend/management/commands/import_hscic_prescribing.py", line 55, in handle
    self.import_shas_and_pcts(f)
  File "/code/openprescribing/frontend/management/commands/import_hscic_prescribing.py", line 67, in import_shas_and_pcts
    rows = csv.reader(open(filename, 'rU'))
IOError: [Errno 2] No such file or directory: 'frontend/tests/fixtures/commands/T201509PDPI+BNFT_formatted.CSV'
```

**Comment by annapowellsmith** [comment]
Odd, I wonder if that's a path error. Can you see that file locally? Are you running the tests from the `manage.py` directory? And are you using `make test` or `manage.py`?

**Comment by annapowellsmith** [comment]
also does `python manage.py test frontend.tests.commands.test_import_hscic_prescribing` run?

**Comment by sebbacon** [comment]
```sh
$  ls -l frontend/tests/fixtures/commands/T201509PDPI+BNFT_formatted.*
-rw-rw-r-- 1 seb seb 1203 May 12 14:04 frontend/tests/fixtures/commands/T201509PDPI+BNFT_formatted.csv
```

It's a case thing - the extension in the tests is in caps, and on the filesystem is lowercase.

Yet when I compare [the test](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/tests/test_api_measures.py#L50) with [the fixture](https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/tests/fixtures/commands/T201304PDPI%2BBNFT_formatted.CSV), they match.

But I have no changes in my local git tree relating to renaming the file. Curiouser and curiouser.

**Comment by sebbacon** [comment]
Ah, no, they don't match. There are two files with similar names, so I was getting them mixed up.

**Comment by sebbacon** [comment]
I missed the following comment from @annapowellsmith by email:

> 1. hscic_prescribing_sample_test.csv is a file that gets generated as
> part of the test, so it doesn't need to be in the codebase:
> https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/tests/commands/test_convert_hscic_prescribing.py#L20-27
> 
> 2. the second one should be in the codebase:
> https://github.com/ebmdatalab/openprescribing/blob/master/openprescribing/frontend/tests/fixtures/commands/T201509PDPI%2BBNFT_formatted.csv
