### ISSUE TITLE
Encoding error in measures calculation

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#159]
```
updating Prescribing of Pioglitazone Hydrochloride (BNF code 0601023B0)  compared with prescrib
ing of all Antidiabetic Drugs (BNF code 6.1.2). for practices in 2016-04-01
creating measurevalue for practice 0 of 7934
<snip>
processing dataframe of length 7934
updating Prescribing of Pioglitazone Hydrochloride (BNF code 0601023B0)  compared with prescribing of all Antidiabetic Drugs (BNF code 6.1.2). for CCGs in 2016-04-01
processing dataframe of length 212
Updating measure: ktt3_lipid_modifying_drugs
updating
Traceback (most recent call last):
  File "/webapps/openprescribing/openprescribing/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/import_measures.py", line 58, in handle
    measure, month, measure_config)
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/import_measures.p
y", line 174, in create_practice_measurevalues
    print 'updating', measure.title, 'for practices in', month
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 151: ordinal not
 in range(128)

```

**Comment by sebbacon** [comment]
This is a 'LEFT SINGLE QUOTATION MARK' unicode character [here](https://github.com/ebmdatalab/openprescribing/blob/7dfa5b2b33a510cfdc2592601560946269e6cc0d/openprescribing/frontend/management/commands/measure_definitions/ktts.json#L16).

I'm stumped as to why this would be causing an encoding error. The obvious reason would be that printing to the console might be the issue if the console's character encoding is set to ASCII.

However, in the screen session that produced that error, the locale appears fine:

```bash
(.venv)hello@OpenPrescribing:~/openprescribing-data$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

...and I'm unable to reproduce the problem, e.g. with `python -c 'print "💩"'`and various other incantations (including running the management command locally).

I'm tempted just to remove the unicode character for the time being, though that just stores up the problem for next time. Any ideas @annapowellsmith?

**Comment by sebbacon** [comment]
Typically, as soon as I posted this I realised that the command is running in a subprocess. I expect the subprocess is not getting the same locale settings as its parent. Investigating further...

**Comment by annapowellsmith** [comment]
I'd be tempted just to remove the print statement...

**Comment by sebbacon** [comment]
Fixed in https://github.com/ebmdatalab/openprescribing-data/commit/569af340d0c71675eb987fe82dc4eb9029c823ce

(which now it's generally proved its worth, really needs tests -- I'd like to do that at the next monthly import)
