### ISSUE TITLE
Drug Tariff parsing issue

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1620]
From `fetch_drug_tariff.sh`:

```
Traceback (most recent call last):
  File "/webapps/openprescribing/openprescribing/manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/webapps/openprescribing/openprescribing/dmd/management/commands/fetch_and_import_drug_tariff.py", line 61, in handle
    date = datetime.date(int(year), month, 1)
ValueError: invalid literal for int() with base 10: '19_0'
```

**Comment by inglesp** [comment]
The filename for the April data is Part%20VIIIA%20Apr%2019_0.xlsx, while for all previous months it's been eg Part%20VIIIA%20Mar%2019.xlsx.  Grr.
