### ISSUE TITLE
Intermittent failure on ImportMeasuresTests.test_import_measures_practice_statistics

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#1678]
The test suite has been intermittently (but quite regularly, for me) failing with this error:
```
======================================================================
FAIL: test_import_measures_practice_statistics (frontend.tests.commands.test_import_measures_new.ImportMeasuresTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/openprescribing/frontend/tests/commands/test_import_measures_new.py", line 415, in test_import_measures_practice_statistics
    self.validate_practice_statistics_measure_value(mv, ccgs.loc[mv.pct_id])
  File "/code/openprescribing/frontend/tests/commands/test_import_measures_new.py", line 587, in validate_practice_statistics_measure_value
    self.assertAlmostEqual(mv.percentile, series['ratio_percentile'])
AssertionError: 35.4838709677419 != 34.67741935483871 within 7 places
```

**Comment by inglesp** [comment]
Yuck.

Next time it happens, can you grab the co-proxamol tables in the`measures_{BQ_NONCE}` dataset in BQ?

**Comment by inglesp** [comment]
Oh, and do you know if it always happens with CCGs?

**Comment by evansd** [comment]
I feel like the error has been identical each time, but I couldn't swear to that so I'll make sure I keep a record next time, as well as grabbing the BQ table.

**Comment by evansd** [comment]
Failed again on the same line, but the precise figures are different:
```
======================================================================
FAIL: test_import_measures_practice_statistics (frontend.tests.commands.test_import_measures_new.ImportMeasuresTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/openprescribing/frontend/tests/commands/test_import_measures_new.py", line 415, in test_import_measures_practice_statistics
    self.validate_practice_statistics_measure_value(mv, ccgs.loc[mv.pct_id])
  File "/code/openprescribing/frontend/tests/commands/test_import_measures_new.py", line 587, in validate_practice_statistics_measure_value
    self.assertAlmostEqual(mv.percentile, series['ratio_percentile'])
AssertionError: 22.5806451612903 != 23.387096774193548 within 7 places
```

**Comment by evansd** [comment]
And again:
```
======================================================================
FAIL: test_import_measures_practice_statistics (frontend.tests.commands.test_import_measures_new.ImportMeasuresTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/openprescribing/frontend/tests/commands/test_import_measures_new.py", line 415, in test_import_measures_practice_statistics
    self.validate_practice_statistics_measure_value(mv, ccgs.loc[mv.pct_id])
  File "/code/openprescribing/frontend/tests/commands/test_import_measures_new.py", line 587, in validate_practice_statistics_measure_value
    self.assertAlmostEqual(mv.percentile, series['ratio_percentile'])
AssertionError: 9.67741935483871 != 8.870967741935484 within 7 places
```
BQ dataset: https://bigquery.cloud.google.com/dataset/ebmdatalabtest:measures_0708

**Comment by evansd** [comment]
This issues seems to be becoming more pressing. I'd say it's happening >50% of the time for me at the moment.
