### ISSUE TITLE
Problem uploading Price Concessions to bigquery

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#1710]
```bash
(.venv)hello@largeweb2:/webapps/openprescribing/openprescribing$ ./manage.py fetch_and_import_ncso_concessions
Traceback (most recent call last):
  File "./manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/webapps/openprescribing/openprescribing/dmd/management/commands/fetch_and_import_ncso_concessions.py", line 30, in handle
    Client('dmd').upload_model(NCSOConcession)
  File "/webapps/openprescribing/openprescribing/gcutils/bigquery.py", line 266, in upload_model
    table.insert_rows_from_pg(model, columns, transformer)
  File "/webapps/openprescribing/openprescribing/gcutils/bigquery.py", line 354, in insert_rows_from_pg
    self.insert_rows_from_csv(f.name, foo='bar')
  File "/webapps/openprescribing/openprescribing/gcutils/bigquery.py", line 346, in insert_rows_from_csv
    default_options)
  File "/webapps/openprescribing/openprescribing/gcutils/bigquery.py", line 289, in run_job
    return self.client.run_job(*args)
  File "/webapps/openprescribing/openprescribing/gcutils/bigquery.py", line 102, in run_job
    return job.result()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/google/cloud/bigquery/job.py", line 528, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/google/api_core/future/polling.py", line 111, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: CSV table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.
```

The actual data in the database looks fine to me:

```
127.0.0.1 prescribing@prescribing=# select * from dmd_ncsoconcession where date = '2019-05-01';
┌──────┬─────────────────────────────────────────────────────────────┬───────────┬────────────────────────┬───────────────────┬────────────┐
│  id  │                            drug                             │ pack_size │ price_concession_pence │      vmpp_id      │    date    │
├──────┼─────────────────────────────────────────────────────────────┼───────────┼────────────────────────┼───────────────────┼────────────┤
│ 3667 │ Amiloride 5mg tablets                                       │ 28        │                    949 │  1191111000001100 │ 2019-05-01 │
│ 3668 │ Betahistine 8mg tablets                                     │ 84        │                    261 │   987211000001103 │ 2019-05-01 │
│ 3669 │ Candesartan 8mg tablets                                     │ 28        │                    250 │  1150111000001102 │ 2019-05-01 │
│ 3670 │ Candesartan 32mg tablets                                    │ 28        │                    249 │  8983811000001102 │ 2019-05-01 │
│ 3671 │ Carvedilol 3.125mg tablets                                  │ 28        │                    116 │  1053911000001103 │ 2019-05-01 │
│ 3672 │ Carvedilol 12.5mg tablets                                   │ 28        │                    220 │  1090311000001102 │ 2019-05-01 │
│ 3673 │ Carvedilol 25mg tablets                                     │ 28        │                    280 │  1080411000001105 │ 2019-05-01 │
│ 3674 │ Celecoxib 100mg capsules                                    │ 60        │                    329 │  1123811000001101 │ 2019-05-01 │
│ 3676 │ Co-careldopa 25mg/100mg tablets                             │ 100       │                    976 │  1114811000001105 │ 2019-05-01 │
│ 3677 │ Ibandronic acid 50mg tablets                                │ 28        │                   5500 │  7540011000001105 │ 2019-05-01 │
│ 3678 │ Ibandronic acid 150mg tablets                               │ 1         │                   1100 │  9544811000001102 │ 2019-05-01 │
│ 3679 │ Irbesartan 150mg tablets                                    │ 28        │                    320 │  1126711000001102 │ 2019-05-01 │
│ 3680 │ Irbesartan 300mg tablets                                    │ 28        │                    400 │  1080311000001103 │ 2019-05-01 │
│ 3681 │ Losartan 100mg tablets                                      │ 28        │                    320 │   988311000001107 │ 2019-05-01 │
│ 3682 │ Metoprolol 100mg tablets                                    │ 28        │                    330 │  1152211000001109 │ 2019-05-01 │
│ 3683 │ Naproxen 250mg tablets                                      │ 28        │                    376 │  1204111000001102 │ 2019-05-01 │
│ 3684 │ Naproxen 250mg gastro-resistant tablets                     │ 56        │                   1000 │  1001411000001102 │ 2019-05-01 │
│ 3685 │ Naproxen 500mg gastro-resistant tablets                     │ 56        │                   1925 │  1212011000001107 │ 2019-05-01 │
│ 3686 │ Nortriptyline 10mg tablets                                  │ 100       │                    574 │  1088711000001102 │ 2019-05-01 │
│ 3687 │ Quetiapine 200mg tablets                                    │ 60        │                   1210 │  1094611000001100 │ 2019-05-01 │
│ 3688 │ Quetiapine 300mg tablets                                    │ 60        │                    721 │  4989011000001105 │ 2019-05-01 │
│ 3689 │ Riluzole 50mg tablets                                       │ 56        │                   6995 │  3684211000001100 │ 2019-05-01 │
│ 3690 │ Sevelamer 800mg tablets                                     │ 180       │                  12797 │ 18290711000001100 │ 2019-05-01 │
│ 3691 │ Telmisartan 20mg tablets                                    │ 28        │                    322 │   995411000001106 │ 2019-05-01 │
│ 3692 │ Telmisartan 80mg tablets                                    │ 28        │                    660 │  1213111000001102 │ 2019-05-01 │
│ 3693 │ Metronidazole 200mg tablets                                 │ 21        │                    231 │  1147311000001101 │ 2019-05-01 │
│ 3695 │ Chloramphenicol 0.5% eye drops                              │ 10ml      │                    216 │  1064411000001101 │ 2019-05-01 │
│ 3696 │ Clomipramine 50mg capsules                                  │ 28        │                    412 │  1313011000001108 │ 2019-05-01 │
│ 3698 │ Dosulepin 75mg tablets                                      │ 28        │                   1259 │  1305411000001103 │ 2019-05-01 │
│ 3699 │ Losartan 12.5mg tablets                                     │ 28        │                    462 │ 15138811000001106 │ 2019-05-01 │
│ 3700 │ Metoprolol 50mg tablets                                     │ 28        │                    623 │  1280211000001101 │ 2019-05-01 │
│ 3701 │ Metronidazole 400mg tablets                                 │ 21        │                    600 │  1255311000001109 │ 2019-05-01 │
│ 3702 │ Pantoprazole 20mg gastro-resistant tablets                  │ 28        │                    425 │  1212911000001106 │ 2019-05-01 │
│ 3694 │ Bumetanide 1mg tablets                                      │ 28        │                    185 │   979611000001100 │ 2019-05-01 │
│ 3697 │ Diamorphine 30mg powder for solution for injection ampoules │ 5         │                   1652 │  1258811000001109 │ 2019-05-01 │
│ 3703 │ Pantoprazole 40mg gastro-resistant tablets                  │ 28        │                    695 │  1278111000001100 │ 2019-05-01 │
│ 3704 │ Quinine bisulfate 300mg tablets                             │ 28        │                    238 │  1018011000001102 │ 2019-05-01 │
│ 3705 │ Quinine sulfate 300mg tablets                               │ 28        │                    379 │  1088311000001101 │ 2019-05-01 │
│ 3706 │ Risedronate sodium 35mg tablets                             │ 4         │                   1160 │  4028111000001103 │ 2019-05-01 │
│ 3707 │ Tibolone 2.5mg tablets                                      │ 28        │                    900 │  1205011000001104 │ 2019-05-01 │
│ 3708 │ Topiramate 100mg tablets                                    │ 60        │                   2183 │  1209511000001105 │ 2019-05-01 │
│ 3709 │ Celecoxib 200mg capsules                                    │ 30        │                   1149 │  1075611000001105 │ 2019-05-01 │
└──────┴─────────────────────────────────────────────────────────────┴───────────┴────────────────────────┴───────────────────┴────────────┘
(42 rows)
```

**Comment by inglesp** [comment]
We haven't seen this recently, and data in BQ is up to date, so closing this.
