### ISSUE TITLE
IOError when loading idna-2.6.dist-info/METADATA

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#1890]
Since upgrading the `idna` library from 2.6 to 2.8 (#1843), we've had these errors:

IOError: [Errno 2] No such file or directory: '/webapps/openprescribing/.venv/lib/python2.7/site-packages/idna-2.6.dist-info/METADATA'

[Sentry](https://sentry.io/organizations/ebm-datalab/issues/1115723922/) was no help, but full tracebacks have turned up in `gunicorn.log`:

<details>
<summary>traceback</summary>

```
2019-07-17 09:59:51,798 ERROR [django.request:135] exception 30312 140133083313600 Internal Server Error: /practice/C82662/measures/
Traceback (most recent call last):
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/webapps/openprescribing/openprescribing/frontend/views/views.py", line 77, in wrapper
    return view_function(request, *args, **kwargs)
  File "/webapps/openprescribing/openprescribing/frontend/views/views.py", line 463, in measures_for_one_practice
    return _measures_for_one_entity(request, practice_code, 'practice')
  File "/webapps/openprescribing/openprescribing/frontend/views/views.py", line 520, in _measures_for_one_entity
    return render(request, 'measures_for_one_entity.html', context)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/template/base.py", line 205, in render
    with context.bind_template(self):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/template/context.py", line 259, in bind_template
    processors = (template.engine.template_context_processors +
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/template/engine.py", line 93, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/template/engine.py", line 93, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/webapps/openprescribing/openprescribing/pipeline/context_processors.py", line 1, in <module>
    from pipeline.runner import in_progress
  File "/webapps/openprescribing/openprescribing/pipeline/runner.py", line 19, in <module>
    from gcutils.storage import Client as StorageClient
  File "/webapps/openprescribing/openprescribing/gcutils/storage.py", line 1, in <module>
    from google.cloud import storage as gcs
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/google/cloud/storage/__init__.py", line 39, in <module>
    from google.cloud.storage.blob import Blob
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/google/cloud/storage/blob.py", line 44, in <module>
    from google.resumable_media.requests import ChunkedDownload
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/google/resumable_media/requests/__init__.py", line 665, in <module>
    pkg_resources.require('requests >= 2.18.0')
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2613, in requires
    dm = self._dep_map
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2864, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2873, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2855, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1404, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1516, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 2] No such file or directory: '/webapps/openprescribing/.venv/lib/python2.7/site-packages/idna-2.6.dist-info/METADATA'

```
</details>

Since upgrading `certifi`, we've also had `IOError`s for `certifi-2017.7.27.1.dist-info/METADATA`.

Most times we've seen this have coincided with deploys, except for a handful first thing this morning.

**Comment by inglesp** [comment]
I can't reproduce from the shell:

```
>>> import pkg_resources
>>> pkg_resources.require('requests >= 2.18.0')
[requests 2.22.0 (/webapps/openprescribing/.venv/lib/python2.7/site-packages), idna 2.8 (/webapps/openprescribing/.venv/lib/python2.7/site-packages), chardet 3.0.4 (/webapps/openprescribing/.venv/lib/python2.7/site-packages), certifi 2019.6.16 (/webapps/openprescribing/.venv/lib/python2.7/site-packages), urllib3 1.25.3 (/webapps/openprescribing/.venv/lib/python2.7/site-packages)]
```

**Comment by evansd** [comment]
Oh, it's just occurred to me that this is a consequence of the fact that we don't actually restart the parent gunicorn process when we deploy: we just send it a signal telling it to reload the application code. This makes deploys that involve updating dependencies inherently unreliable.

The immediate solution is to do a full stop and restart of the supervisor process. The longer term solution is to stop using this approach to graceful restarts. Systemd provides a mechanism that is much more reliable.

**Comment by inglesp** [comment]
Suspect you're right.

**Comment by evansd** [comment]
No need to track this in a separate issue now, I think
