### ISSUE TITLE
Errors thrown by functional tests

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#2379]
We had the first flaky failure on the functional tests that we've seen in a long while. This isn't itself too troubling as these are much less frequent than they used to be and a certain amount of flakiness is inevitable with the convoluted remote browser setup. However I noticed when looking at it that the functional tests are throwing a lot of errors like this:
```
----------------------------------------
Exception happened during processing of request from ('172.18.0.1', 37630)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 721, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/code/openprescribing/frontend/tests/functional/mock_api_server.py", line 104, in do_GET
    self.wfile.write(data.encode("utf8"))
AttributeError: 'dict' object has no attribute 'encode'
----------------------------------------
```
(From https://travis-ci.org/ebmdatalab/openprescribing/jobs/633828763 although this log won't stick around forever)

This is note to myself (mainly) to look into this at some point.

**Comment by evansd** [comment]
Fixed in #2808
