### ISSUE TITLE
Clean up unhandlable alerts

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#2434]
Since we batch-approved long-pending alert signups, we now have a lot more errors during sending - so many that the error-batching functionality exits with large batches.

I'm running alerts for Nov now in a screen session, as ` ./manage.py send_monthly_alerts --max_errors=500`.

We should return to its output, classify the errors, and decide how to clean things up. 

It's already clear some of these are alerts we probably shouldn't support, such as this one for every single practice in one analyze chart:

```
common.alert_utils.BatchedEmailErrors: subprocess.CalledProcessError: Command '/usr/local/bin/phantomjs /webapps/openprescribing/openprescribing/frontend/management/commands/grab_chart.js "https://openprescribing.net/analyse/#org=practice&orgIds=03L,02N,00T,99C,01A,00N,01C,00L,00Q,02W,01H,01K,03F,03A,03H,00V,08K,05D,00Y,01W,01Y,02A,06M,01J,01T,01V,12F,01X,09X,03D,04E,04C,15C,05Y,03Q,03T,05L,04G,03V,04H,04L,07W,08C,07Y,04K,07R,04Y,05N,05C,08P,05F,05Q,08L,07V,09D,05T,10C,10K,08H,06H,06L,06Q,10X,00R,02T,07L,00K,99A,06Y,07J,03J,10L,07K,07M,07Q,09G,10Q,10R,06P,10E,07G,02H,14L,11A,00C,04M,11J,07T,11M,03W,11N,11X,14Y,15M,07X,15N,99J,11E,99N,02E,00P,02M,99F,08W,08M,02F,08E,02P,03E,08V,08Q,03M,08T,08X,00X,04F,09E,09Y,04V,05R,05W,06F,06T,02Y,01R,06V,07H,05G,09N,10J,15E,08Y,05V,15A,08D,99D,08A,99K,05H,09A,09J,05X,09C,99E,00D,08R,15D,06N,99G,01E,01F,03R,06D,06K,02X,10D,09F,06A,02G,00M,06W,02R,03N,05A,01G,04N,03K,09W,02D,07P,02Q,13T,00J,07N,08N,15F,01D,04Q,05J,09L,09P,10V,04D,08G,08F,08J,10A,09H,12D,99M,99H&numIds=0109040N0BD&denom=nothing&selectedTab=summary" /mnt/database/tmp/tmp7f1j3tbd.png "#results .tab-pane.active" 800x600 500' returned non-zero exit status 139
```

**Comment by sebbacon** [comment]
Oh, didn't get far at all:

```
Traceback (most recent call last):
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/send_monthly_alerts.py", line 232, in handle
    self.send_org_bookmark_email, org_bookmark, now_month, options
  File "/webapps/openprescribing/openprescribing/common/alert_utils.py", line 44, in try_email
    if len(self.exceptions) > self.max_errors:
TypeError: unorderable types: int() > str()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/webapps/openprescribing/.venv35/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/webapps/openprescribing/.venv35/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/webapps/openprescribing/.venv35/lib/python3.5/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/webapps/openprescribing/.venv35/lib/python3.5/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/send_monthly_alerts.py", line 237, in handle
    self.send_search_bookmark_email, search_bookmark, now_month
  File "/webapps/openprescribing/openprescribing/common/alert_utils.py", line 53, in __exit__
    raise exception
common.alert_utils.BatchedEmailErrors: anymail.exceptions.AnymailRequestsAPIError: Sending a message to XXXX@gp-l81047.nhs.nt from OpenPrescribing <feedback@openprescribing.net>
Mailgun API response 400 (BAD REQUEST):
{
  "message": "'to' parameter is not a valid address. please check documentation"
}
```

Clearly the mailgun API has stopped accepting invalid email addresses (or we've suddently got a lot more).

**Comment by evansd** [comment]
We don't actually have that many bad email addresses in the database (list [here](https://github.com/ebmdatalab/sysadmin/issues/82)). Quite a few of these are obvious typos and have obvious fixes so we could apply those if we thought that was sensible and delete the rest.

I used [this script](https://gist.github.com/evansd/cb2658d0e2277f64bbee20e7394dcf5a) to find them, which uses Mailgun's [flanker](https://github.com/mailgun/flanker) library which goes beyond syntactic validation and checks that the domain exists and can receive email. It also has some fun features like suggesting fixes for common typos. It's fairly easy to swap it in for Django's default email validation so possibly we should consider that.

**Comment by evansd** [comment]
Only just spotted that the reason it didn't get far above is that there's an error in the `max_errors` handling code, not because it hit 500 errors:
```
    if len(self.exceptions) > self.max_errors:
TypeError: unorderable types: int() > str()
```
Looks easy enough to fix though.

**Comment by evansd** [comment]
I've marked as inactive all the bad email addresses listed above. Ideally I would have deleted them, but it's slightly complex to do that due to the various foreign key relations.

**Comment by sebbacon** [comment]
Latest run finished with a segfault: 
<details><summary>full output</summary>

```
.venv35) hello@largeweb2:/webapps/openprescribing/openprescribing$ ./manage.py send_monthly_alerts
/webapps/openprescribing/openprescribing/frontend/views/bookmark_utils.py:204: RuntimeWarning: Mean of empty slice
  self.target_means.append(np.nanmean(window))
/webapps/openprescribing/.venv35/lib/python3.5/site-packages/numpy/lib/nanfunctions.py:1667: RuntimeWarning: Degrees of freedom <= 0 for slice.
  keepdims=keepdims)
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'q.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'r.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'q.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'q.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'q.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'q.getEntries()')
console: [opttick] - GTM-5PX77GZ: exception: TypeError: undefined is not a function (evaluating 'q.getEntries()')
1   0x1b67967 /usr/local/bin/phantomjs() [0x1b67967]
2   0x1baac35 /usr/local/bin/phantomjs() [0x1baac35]
3   0x1b9369c /usr/local/bin/phantomjs() [0x1b9369c]
4   0x18970ad /usr/local/bin/phantomjs() [0x18970ad]
5   0x1896ace /usr/local/bin/phantomjs() [0x1896ace]
6   0x1896ddf /usr/local/bin/phantomjs() [0x1896ddf]
7   0x1907ec8 /usr/local/bin/phantomjs() [0x1907ec8]
8   0x7f6d47b398ac [0x7f6d47b398ac]
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Segmentation fault
Command '/usr/local/bin/phantomjs /webapps/openprescribing/openprescribing/frontend/management/commands/grab_chart.js "https://openprescribing.net/analyse/#org=practice&orgIds=03L,02N,00T,99C,01A,00N,01C,00L,00Q,02W,01H,01K,03F,03A,03H,00V,08K,05D,00Y,01W,01Y,02A,06M,01J,01T,01V,12F,01X,09X,03D,04E,04C,15C,05Y,03Q,03T,05L,04G,03V,04H,04L,07W,08C,07Y,04K,07R,04Y,05N,05C,08P,05F,05Q,08L,07V,09D,05T,10C,10K,08H,06H,06L,06Q,10X,00R,02T,07L,00K,99A,06Y,07J,03J,10L,07K,07M,07Q,09G,10Q,10R,06P,10E,07G,02H,14L,11A,00C,04M,11J,07T,11M,03W,11N,11X,14Y,15M,07X,15N,99J,11E,99N,02E,00P,02M,99F,08W,08M,02F,08E,02P,03E,08V,08Q,03M,08T,08X,00X,04F,09E,09Y,04V,05R,05W,06F,06T,02Y,01R,06V,07H,05G,09N,10J,15E,08Y,05V,15A,08D,99D,08A,99K,05H,09A,09J,05X,09C,99E,00D,08R,15D,06N,99G,01E,01F,03R,06D,06K,02X,10D,09F,06A,02G,00M,06W,02R,03N,05A,01G,04N,03K,09W,02D,07P,02Q,13T,00J,07N,08N,15F,01D,04Q,05J,09L,09P,10V,04D,08G,08F,08J,10A,09H,12D,99M,99H&numIds=0109040N0BD&denom=nothing&selectedTab=summary" /mnt/database/tmp/tmpwcqc3mr1.png "#results .tab-pane.active" 800x600 500' returned non-zero exit status 139
Traceback (most recent call last):
  File "/webapps/openprescribing/openprescribing/common/alert_utils.py", line 40, in try_email
    callback(*args)
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/send_monthly_alerts.py", line 181, in send_search_bookmark_email
    msg = bookmark_utils.make_search_email(search_bookmark, tag=now_month)
  File "/webapps/openprescribing/openprescribing/frontend/views/bookmark_utils.py", line 774, in make_search_email
    "#results .tab-pane.active",
  File "/webapps/openprescribing/openprescribing/frontend/views/bookmark_utils.py", line 514, in attach_image
    result = subprocess.check_output(cmd, shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/usr/local/bin/phantomjs /webapps/openprescribing/openprescribing/frontend/management/commands/grab_chart.js "https://openprescribing.net/analyse/#org=practice&orgIds=03L,02N,00T,99C,01A,00N,01C,00L,00Q,02W,01H,01K,03F,03A,03H,00V,08K,05D,00Y,01W,01Y,02A,06M,01J,01T,01V,12F,01X,09X,03D,04E,04C,15C,05Y,03Q,03T,05L,04G,03V,04H,04L,07W,08C,07Y,04K,07R,04Y,05N,05C,08P,05F,05Q,08L,07V,09D,05T,10C,10K,08H,06H,06L,06Q,10X,00R,02T,07L,00K,99A,06Y,07J,03J,10L,07K,07M,07Q,09G,10Q,10R,06P,10E,07G,02H,14L,11A,00C,04M,11J,07T,11M,03W,11N,11X,14Y,15M,07X,15N,99J,11E,99N,02E,00P,02M,99F,08W,08M,02F,08E,02P,03E,08V,08Q,03M,08T,08X,00X,04F,09E,09Y,04V,05R,05W,06F,06T,02Y,01R,06V,07H,05G,09N,10J,15E,08Y,05V,15A,08D,99D,08A,99K,05H,09A,09J,05X,09C,99E,00D,08R,15D,06N,99G,01E,01F,03R,06D,06K,02X,10D,09F,06A,02G,00M,06W,02R,03N,05A,01G,04N,03K,09W,02D,07P,02Q,13T,00J,07N,08N,15F,01D,04Q,05J,09L,09P,10V,04D,08G,08F,08J,10A,09H,12D,99M,99H&numIds=0109040N0BD&denom=nothing&selectedTab=summary" /mnt/database/tmp/tmpwcqc3mr1.png "#results .tab-pane.active" 800x600 500' returned non-zero exit status 139
Traceback (most recent call last):
  File "./manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/webapps/openprescribing/.venv35/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/webapps/openprescribing/.venv35/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/webapps/openprescribing/.venv35/lib/python3.5/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/webapps/openprescribing/.venv35/lib/python3.5/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/send_monthly_alerts.py", line 237, in handle
    self.send_search_bookmark_email, search_bookmark, now_month
  File "/webapps/openprescribing/openprescribing/common/alert_utils.py", line 53, in __exit__
    raise exception
common.alert_utils.BatchedEmailErrors: subprocess.CalledProcessError: Command '/usr/local/bin/phantomjs /webapps/openprescribing/openprescribing/frontend/management/commands/grab_chart.js "https://openprescribing.net/analyse/#org=practice&orgIds=03L,02N,00T,99C,01A,00N,01C,00L,00Q,02W,01H,01K,03F,03A,03H,00V,08K,05D,00Y,01W,01Y,02A,06M,01J,01T,01V,12F,01X,09X,03D,04E,04C,15C,05Y,03Q,03T,05L,04G,03V,04H,04L,07W,08C,07Y,04K,07R,04Y,05N,05C,08P,05F,05Q,08L,07V,09D,05T,10C,10K,08H,06H,06L,06Q,10X,00R,02T,07L,00K,99A,06Y,07J,03J,10L,07K,07M,07Q,09G,10Q,10R,06P,10E,07G,02H,14L,11A,00C,04M,11J,07T,11M,03W,11N,11X,14Y,15M,07X,15N,99J,11E,99N,02E,00P,02M,99F,08W,08M,02F,08E,02P,03E,08V,08Q,03M,08T,08X,00X,04F,09E,09Y,04V,05R,05W,06F,06T,02Y,01R,06V,07H,05G,09N,10J,15E,08Y,05V,15A,08D,99D,08A,99K,05H,09A,09J,05X,09C,99E,00D,08R,15D,06N,99G,01E,01F,03R,06D,06K,02X,10D,09F,06A,02G,00M,06W,02R,03N,05A,01G,04N,03K,09W,02D,07P,02Q,13T,00J,07N,08N,15F,01D,04Q,05J,09L,09P,10V,04D,08G,08F,08J,10A,09H,12D,99M,99H&numIds=0109040N0BD&denom=nothing&selectedTab=summary" /mnt/database/tmp/tmpwcqc3mr1.png "#results .tab-pane.active" 800x600 500' returned non-zero exit status 139
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```
</details>
Resuming with `--max_errors=50`
