### ISSUE TITLE
"Ansible buildout test" is broken

### ISSUE THREAD

**Issue by evansd** [ebmdatalab/openprescribing#2943]
See e.g. #2942 

From a quick glance this looks like a syntax error on a f-string, which suggests some unpinned dependency somewhere has upgraded to the point where it no longer supports Python <3.7 and Ansible is using some older version.

Log output below
```
Run docker run -v ${GITHUB_WORKSPACE}:/openprescribing/ dockette/stretch /bin/bash -c "cd /openprescribing/ansible && bash test_playbook.sh"
Unable to find image 'dockette/stretch:latest' locally
latest: Pulling from dockette/stretch
3192219afd04: Pulling fs layer
587d748ee0cc: Pulling fs layer
587d748ee0cc: Verifying Checksum
587d748ee0cc: Download complete
3192219afd04: Verifying Checksum
3192219afd04: Download complete
3192219afd04: Pull complete
587d748ee0cc: Pull complete
Digest: sha256:2c2e2117dd50037752bb0b0fc2cafd3dd5ceffa03c2b2e45eaa8bedea1359da3
Status: Downloaded newer image for dockette/stretch:latest
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://security.debian.org/debian-security stretch/updates InRelease [53.0 kB]
Get:3 http://deb.debian.org/debian stretch-updates InRelease [93.6 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://deb.debian.org/debian stretch Release.gpg [2410 B]
Get:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [649 kB]
Get:7 http://deb.debian.org/debian stretch-updates/main amd64 Packages [2596 B]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [7080 kB]
Fetched 7998 kB in 1s (5752 kB/s)
Reading package lists...
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libssl1.1:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 6500 files and directories currently installed.)
Preparing to unpack .../00-libssl1.1_1.1.0l-1~deb9u2_amd64.deb ...
Unpacking libssl1.1:amd64 (1.1.0l-1~deb9u2) ...
Selecting previously unselected package libpython3.5-minimal:amd64.
Preparing to unpack .../01-libpython3.5-minimal_3.5.3-1+deb9u3_amd64.deb ...
Unpacking libpython3.5-minimal:amd64 (3.5.3-1+deb9u3) ...
Selecting previously unselected package libexpat1:amd64.
Preparing to unpack .../02-libexpat1_2.2.0-2+deb9u3_amd64.deb ...
Unpacking libexpat1:amd64 (2.2.0-2+deb9u3) ...
Selecting previously unselected package python3.5-minimal.
Preparing to unpack .../03-python3.5-minimal_3.5.3-1+deb9u3_amd64.deb ...
Unpacking python3.5-minimal (3.5.3-1+deb9u3) ...
Selecting previously unselected package python3-minimal.
Preparing to unpack .../04-python3-minimal_3.5.3-1_amd64.deb ...
Unpacking python3-minimal (3.5.3-1) ...
Selecting previously unselected package mime-support.
Preparing to unpack .../05-mime-support_3.60_all.deb ...
Unpacking mime-support (3.60) ...
Selecting previously unselected package libmpdec2:amd64.
Preparing to unpack .../06-libmpdec2_2.4.2-1_amd64.deb ...
Unpacking libmpdec2:amd64 (2.4.2-1) ...
Selecting previously unselected package readline-common.
Preparing to unpack .../07-readline-common_7.0-3_all.deb ...
Unpacking readline-common (7.0-3) ...
Selecting previously unselected package libreadline7:amd64.
Preparing to unpack .../08-libreadline7_7.0-3_amd64.deb ...
Unpacking libreadline7:amd64 (7.0-3) ...
Selecting previously unselected package libsqlite3-0:amd64.
Preparing to unpack .../09-libsqlite3-0_3.16.2-5+deb9u3_amd64.deb ...
Unpacking libsqlite3-0:amd64 (3.16.2-5+deb9u3) ...
Selecting previously unselected package libpython3.5-stdlib:amd64.
Preparing to unpack .../10-libpython3.5-stdlib_3.5.3-1+deb9u3_amd64.deb ...
Unpacking libpython3.5-stdlib:amd64 (3.5.3-1+deb9u3) ...
Selecting previously unselected package python3.5.
Preparing to unpack .../11-python3.5_3.5.3-1+deb9u3_amd64.deb ...
Unpacking python3.5 (3.5.3-1+deb9u3) ...
Selecting previously unselected package libpython3-stdlib:amd64.
Preparing to unpack .../12-libpython3-stdlib_3.5.3-1_amd64.deb ...
Unpacking libpython3-stdlib:amd64 (3.5.3-1) ...
Selecting previously unselected package dh-python.
Preparing to unpack .../13-dh-python_2.20170125_all.deb ...
Unpacking dh-python (2.20170125) ...
Setting up libssl1.1:amd64 (1.1.0l-1~deb9u2) ...
Setting up libpython3.5-minimal:amd64 (3.5.3-1+deb9u3) ...
Setting up libexpat1:amd64 (2.2.0-2+deb9u3) ...
Setting up python3.5-minimal (3.5.3-1+deb9u3) ...
Setting up python3-minimal (3.5.3-1) ...
Selecting previously unselected package python3.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 7493 files and directories currently installed.)
Preparing to unpack .../00-python3_3.5.3-1_amd64.deb ...
Unpacking python3 (3.5.3-1) ...
Selecting previously unselected package libssl1.0.2:amd64.
Preparing to unpack .../01-libssl1.0.2_1.0.2u-1~deb9u3_amd64.deb ...
Unpacking libssl1.0.2:amd64 (1.0.2u-1~deb9u3) ...
Selecting previously unselected package bzip2.
Preparing to unpack .../02-bzip2_1.0.6-8.1_amd64.deb ...
Unpacking bzip2 (1.0.6-8.1) ...
Selecting previously unselected package libmagic-mgc.
Preparing to unpack .../03-libmagic-mgc_1%3a5.30-1+deb9u3_amd64.deb ...
Unpacking libmagic-mgc (1:5.30-1+deb9u3) ...
Selecting previously unselected package libmagic1:amd64.
Preparing to unpack .../04-libmagic1_1%3a5.30-1+deb9u3_amd64.deb ...
Unpacking libmagic1:amd64 (1:5.30-1+deb9u3) ...
Selecting previously unselected package file.
Preparing to unpack .../05-file_1%3a5.30-1+deb9u3_amd64.deb ...
Unpacking file (1:5.30-1+deb9u3) ...
Selecting previously unselected package krb5-locales.
Preparing to unpack .../06-krb5-locales_1.15-1+deb9u2_all.deb ...
Unpacking krb5-locales (1.15-1+deb9u2) ...
Selecting previously unselected package libc-l10n.
Preparing to unpack .../07-libc-l10n_2.24-11+deb9u4_all.deb ...
Unpacking libc-l10n (2.24-11+deb9u4) ...
Selecting previously unselected package libgmp10:amd64.
Preparing to unpack .../08-libgmp10_2%3a6.1.2+dfsg-1_amd64.deb ...
Unpacking libgmp10:amd64 (2:6.1.2+dfsg-1) ...
Selecting previously unselected package libhogweed4:amd64.
Preparing to unpack .../09-libhogweed4_3.3-1+b2_amd64.deb ...
Unpacking libhogweed4:amd64 (3.3-1+b2) ...
Selecting previously unselected package libffi6:amd64.
Preparing to unpack .../10-libffi6_3.2.1-6_amd64.deb ...
Unpacking libffi6:amd64 (3.2.1-6) ...
Selecting previously unselected package libp11-kit0:amd64.
Preparing to unpack .../11-libp11-kit0_0.23.3-2+deb9u1_amd64.deb ...
Unpacking libp11-kit0:amd64 (0.23.3-2+deb9u1) ...
Selecting previously unselected package libtasn1-6:amd64.
Preparing to unpack .../12-libtasn1-6_4.10-1.1+deb9u1_amd64.deb ...
Unpacking libtasn1-6:amd64 (4.10-1.1+deb9u1) ...
Selecting previously unselected package libgnutls30:amd64.
Preparing to unpack .../13-libgnutls30_3.5.8-5+deb9u5_amd64.deb ...
Unpacking libgnutls30:amd64 (3.5.8-5+deb9u5) ...
Selecting previously unselected package libkeyutils1:amd64.
Preparing to unpack .../14-libkeyutils1_1.5.9-9_amd64.deb ...
Unpacking libkeyutils1:amd64 (1.5.9-9) ...
Selecting previously unselected package libkrb5support0:amd64.
Preparing to unpack .../15-libkrb5support0_1.15-1+deb9u2_amd64.deb ...
Unpacking libkrb5support0:amd64 (1.15-1+deb9u2) ...
Selecting previously unselected package libk5crypto3:amd64.
Preparing to unpack .../16-libk5crypto3_1.15-1+deb9u2_amd64.deb ...
Unpacking libk5crypto3:amd64 (1.15-1+deb9u2) ...
Selecting previously unselected package libkrb5-3:amd64.
Preparing to unpack .../17-libkrb5-3_1.15-1+deb9u2_amd64.deb ...
Unpacking libkrb5-3:amd64 (1.15-1+deb9u2) ...
Selecting previously unselected package libgssapi-krb5-2:amd64.
Preparing to unpack .../18-libgssapi-krb5-2_1.15-1+deb9u2_amd64.deb ...
Unpacking libgssapi-krb5-2:amd64 (1.15-1+deb9u2) ...
Selecting previously unselected package libsasl2-modules-db:amd64.
Preparing to unpack .../19-libsasl2-modules-db_2.1.27~101-g0780600+dfsg-3+deb9u1_amd64.deb ...
Unpacking libsasl2-modules-db:amd64 (2.1.27~101-g0780600+dfsg-3+deb9u1) ...
Selecting previously unselected package libsasl2-2:amd64.
Preparing to unpack .../20-libsasl2-2_2.1.27~101-g0780600+dfsg-3+deb9u1_amd64.deb ...
Unpacking libsasl2-2:amd64 (2.1.27~101-g0780600+dfsg-3+deb9u1) ...
Selecting previously unselected package libldap-common.
Preparing to unpack .../21-libldap-common_2.4.44+dfsg-5+deb9u7_all.deb ...
Unpacking libldap-common (2.4.44+dfsg-5+deb9u7) ...
Selecting previously unselected package libldap-2.4-2:amd64.
Preparing to unpack .../22-libldap-2.4-2_2.4.44+dfsg-5+deb9u7_amd64.deb ...
Unpacking libldap-2.4-2:amd64 (2.4.44+dfsg-5+deb9u7) ...
Selecting previously unselected package locales.
Preparing to unpack .../23-locales_2.24-11+deb9u4_all.deb ...
Unpacking locales (2.24-11+deb9u4) ...
Selecting previously unselected package xz-utils.
Preparing to unpack .../24-xz-utils_5.2.2-1.2+b1_amd64.deb ...
Unpacking xz-utils (5.2.2-1.2+b1) ...
Selecting previously unselected package openssl.
Preparing to unpack .../25-openssl_1.1.0l-1~deb9u2_amd64.deb ...
Unpacking openssl (1.1.0l-1~deb9u2) ...
Selecting previously unselected package ca-certificates.
Preparing to unpack .../26-ca-certificates_20200601~deb9u1_all.deb ...
Unpacking ca-certificates (20200601~deb9u1) ...
Selecting previously unselected package libunistring0:amd64.
Preparing to unpack .../27-libunistring0_0.9.6+really0.9.3-0.1_amd64.deb ...
Unpacking libunistring0:amd64 (0.9.6+really0.9.3-0.1) ...
Selecting previously unselected package libidn2-0:amd64.
Preparing to unpack .../28-libidn2-0_0.16-1+deb9u1_amd64.deb ...
Unpacking libidn2-0:amd64 (0.16-1+deb9u1) ...
Selecting previously unselected package libnghttp2-14:amd64.
Preparing to unpack .../29-libnghttp2-14_1.18.1-1+deb9u1_amd64.deb ...
Unpacking libnghttp2-14:amd64 (1.18.1-1+deb9u1) ...
Selecting previously unselected package libpsl5:amd64.
Preparing to unpack .../30-libpsl5_0.17.0-3_amd64.deb ...
Unpacking libpsl5:amd64 (0.17.0-3) ...
Selecting previously unselected package librtmp1:amd64.
Preparing to unpack .../31-librtmp1_2.4+20151223.gitfa8646d.1-1+b1_amd64.deb ...
Unpacking librtmp1:amd64 (2.4+20151223.gitfa8646d.1-1+b1) ...
Selecting previously unselected package libssh2-1:amd64.
Preparing to unpack .../32-libssh2-1_1.7.0-1+deb9u1_amd64.deb ...
Unpacking libssh2-1:amd64 (1.7.0-1+deb9u1) ...
Selecting previously unselected package libcurl3:amd64.
Preparing to unpack .../33-libcurl3_7.52.1-5+deb9u13_amd64.deb ...
Unpacking libcurl3:amd64 (7.52.1-5+deb9u13) ...
Selecting previously unselected package curl.
Preparing to unpack .../34-curl_7.52.1-5+deb9u13_amd64.deb ...
Unpacking curl (7.52.1-5+deb9u13) ...
Selecting previously unselected package libsasl2-modules:amd64.
Preparing to unpack .../35-libsasl2-modules_2.1.27~101-g0780600+dfsg-3+deb9u1_amd64.deb ...
Unpacking libsasl2-modules:amd64 (2.1.27~101-g0780600+dfsg-3+deb9u1) ...
Selecting previously unselected package publicsuffix.
Preparing to unpack .../36-publicsuffix_20190415.1030-0+deb9u1_all.deb ...
Unpacking publicsuffix (20190415.1030-0+deb9u1) ...
Setting up readline-common (7.0-3) ...
Setting up libnghttp2-14:amd64 (1.18.1-1+deb9u1) ...
Setting up mime-support (3.60) ...
Setting up libldap-common (2.4.44+dfsg-5+deb9u7) ...
Setting up libreadline7:amd64 (7.0-3) ...
Setting up libsasl2-modules-db:amd64 (2.1.27~101-g0780600+dfsg-3+deb9u1) ...
Setting up libsasl2-2:amd64 (2.1.27~101-g0780600+dfsg-3+deb9u1) ...
Setting up libtasn1-6:amd64 (4.10-1.1+deb9u1) ...
Setting up libmagic-mgc (1:5.30-1+deb9u3) ...
Setting up bzip2 (1.0.6-8.1) ...
Setting up libmagic1:amd64 (1:5.30-1+deb9u3) ...
Setting up libssl1.0.2:amd64 (1.0.2u-1~deb9u3) ...
Setting up libgmp10:amd64 (2:6.1.2+dfsg-1) ...
Setting up libssh2-1:amd64 (1.7.0-1+deb9u1) ...
Setting up krb5-locales (1.15-1+deb9u2) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Setting up publicsuffix (20190415.1030-0+deb9u1) ...
Setting up libunistring0:amd64 (0.9.6+really0.9.3-0.1) ...
Setting up xz-utils (5.2.2-1.2+b1) ...
update-alternatives: using /usr/bin/xz to provide /usr/bin/lzma (lzma) in auto mode
Setting up libc-l10n (2.24-11+deb9u4) ...
Setting up openssl (1.1.0l-1~deb9u2) ...
Setting up libsqlite3-0:amd64 (3.16.2-5+deb9u3) ...
Setting up libffi6:amd64 (3.2.1-6) ...
Setting up libkeyutils1:amd64 (1.5.9-9) ...
Setting up libsasl2-modules:amd64 (2.1.27~101-g0780600+dfsg-3+deb9u1) ...
Setting up ca-certificates (20200601~deb9u1) ...
Updating certificates in /etc/ssl/certs...
126 added, 0 removed; done.
Setting up locales (2.24-11+deb9u4) ...
Generating locales (this might take a while)...
Generation complete.
Setting up libmpdec2:amd64 (2.4.2-1) ...
Setting up libidn2-0:amd64 (0.16-1+deb9u1) ...
Setting up libpsl5:amd64 (0.17.0-3) ...
Setting up libpython3.5-stdlib:amd64 (3.5.3-1+deb9u3) ...
Setting up file (1:5.30-1+deb9u3) ...
Setting up libkrb5support0:amd64 (1.15-1+deb9u2) ...
Setting up libhogweed4:amd64 (3.3-1+b2) ...
Setting up libp11-kit0:amd64 (0.23.3-2+deb9u1) ...
Setting up python3.5 (3.5.3-1+deb9u3) ...
Setting up libpython3-stdlib:amd64 (3.5.3-1) ...
Setting up libk5crypto3:amd64 (1.15-1+deb9u2) ...
Setting up libgnutls30:amd64 (3.5.8-5+deb9u5) ...
Setting up librtmp1:amd64 (2.4+20151223.gitfa8646d.1-1+b1) ...
Setting up libldap-2.4-2:amd64 (2.4.44+dfsg-5+deb9u7) ...
Setting up libkrb5-3:amd64 (1.15-1+deb9u2) ...
Setting up libgssapi-krb5-2:amd64 (1.15-1+deb9u2) ...
Setting up libcurl3:amd64 (7.52.1-5+deb9u13) ...
Setting up curl (7.52.1-5+deb9u13) ...
Setting up python3 (3.5.3-1) ...
Setting up dh-python (2.20170125) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Processing triggers for ca-certificates (20200601~deb9u1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1884k  100 1884k    0     0  9644k      0 --:--:-- --:--:-- --:--:-- 9664k
Traceback (most recent call last):
  File "<stdin>", line 24244, in <module>
  File "<stdin>", line 199, in main
  File "<stdin>", line 82, in bootstrap
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1147, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1104, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 541, in spec_from_file_location
  File "/tmp/tmpobgm9thd/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
Error: Process completed with exit code 1.
```

**Comment by madwort** [comment]
I think this might be the pip installer itself - trying out a pin to 3.5 https://github.com/ebmdatalab/openprescribing/pull/2944/checks?check_run_id=1831364906

**Comment by madwort** [comment]
seems to work
