### ISSUE TITLE
Post-mortem first set of alerts

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#298]
* How many have attempted to sign up?
* How many have succeeded? 
  * What are some reasons for failures to sign up?
* How many received emails?
* How many opened emails?

Also, create an Analytics report for this kind of thing

**Comment by sebbacon** [comment]
There are 75 verified accounts and 64 unverified accounts.

One of the unverified accounts has been receiving emails and clicking links (possibly because I manually verified it...)

23 have clicked links according to our database; 28 according to analytics (this could be the same people using different browsers)

21 have not received any emails, according to our database (and none have clicked links, either).

Our database shows a number who have clicked links but not opened emails -- this will be due to email client settings not tracking opens.



-

**Comment by sebbacon** [comment]
Looks like they didn't all get sent:

```bash
(.venv)hello@openprescribing-with-volumn:/webapps/openprescribing/openprescribing$ python manage.py send_monthly_alerts --settings=openprescribing.settings.production
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/send_monthly_alerts.py", line 94, in handle
    search_bookmark)
  File "/webapps/openprescribing/openprescribing/frontend/views/bookmark_utils.py", line 494, in make_search_email
    '#results .tab-pane.active'
  File "/webapps/openprescribing/openprescribing/frontend/views/bookmark_utils.py", line 299, in attach_image
    result = subprocess.check_output(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '/usr/local/bin/phantomjs /webapps/openprescribing/openprescribing/frontend/management/commands/grab_chart.js "https://openprescribing.net/analyse/#org=practice&orgIds=11X&numIds=4.10.2&denom=total_list_size&selectedTab=summary&source=pageload" /tmp/tmp3LOJEl.png "#results .tab-pane.active" 800x600 500' returned non-zero exit status 1
```

**Comment by sebbacon** [comment]
I've analysed the mailgun logs and a total of 54 monthly updates (not including EMB DataLab people) were sent, so I need to review the error above and work out which recipients still need sending.
