### ISSUE TITLE
Command op_ncso_send_alerts failed

### ISSUE THREAD

**Issue by madwort** [ebmdatalab/openprescribing#3159]
```
Traceback (most recent call last):
  File "/webapps/openprescribing/openprescribing/common/alert_utils.py", line 40, in try_email
    callback(*args)
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/send_ncso_concessions_alerts.py", line 56, in send_alert
    msg = bookmark_utils.make_ncso_concession_email(bookmark, tag=date)
  File "/webapps/openprescribing/openprescribing/frontend/views/bookmark_utils.py", line 807, in make_ncso_concession_email
    latest_month = max(row["month"] for row in monthly_totals)
ValueError: max() arg is an empty sequence
```

just done a quick triage of this - cross-referenced the list of alerts sent out (25) 

```sql
select recipient, timestamp from frontend_maillog where timestamp > '2021-07-14 14:16:00+00' AND timestamp < '2021-07-14 14:20:00+00' order by id desc  ;
```

against the list of alerts that should have been sent out (211) -

```sql
select frontend_ncsoconcessionbookmark.*,auth_user.username from frontend_ncsoconcessionbookmark inner join auth_user on frontend_ncsoconcessionbookmark.user_id = auth_user.id  order by auth_user.id  asc;
```

 if I order by auth_user.id the first 25 usernames look very much like the list of the alerts that were sent out, and the first username after that is for an alert on a CCG that (a quick search engine search) looks like it’s been merged - `05Y` - which would align with the “empty sequence” error above.

Removing this person’s failing alert might unblock more of the list, though a better fix is to gracefully handle this in the code

**Comment by inglesp** [comment]
There are a handful of alerts for CCGs that don't have practices anymore -- these are closed CCGs.  I've updated the alerts with the CCG that replaces them.  (Details of CCG changes [here](https://digital.nhs.uk/services/organisation-data-service/change-summary-reconfiguration-2021-ccg-mergers).)

This was fairly manual.  We'll have to do the same for the organisation alerts -- there are more of these, so we may want to scrape the changes.

**Comment by madwort** [comment]
> We'll have to do the same for the organisation alerts -- there are more of these, so we may want to scrape the changes.

sounds good.

In the meantime, updating the code to output more useful logs might be worth doing (i.e. catching the ValueError & re-throwing the values that triggered it would speed up the manual process a lot). At 211 items, it's not a huge list.

**Comment by inglesp** [comment]
here's a CSV file with the changes:

[ccg-changes.csv](https://github.com/ebmdatalab/openprescribing/files/6846736/ccg-changes.csv)

**Comment by richiecroker** [comment]
another one that can be closed? @madwort @inglesp
