### ISSUE TITLE
Mailgun 404 error on monthly email alerts

### ISSUE THREAD

**Issue by madwort** [ebmdatalab/openprescribing#3610]
This month's email alerts have thrown an unusual error:

```
Traceback (most recent call last):
  File "./manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/webapps/openprescribing/.venv38/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/webapps/openprescribing/.venv38/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/webapps/openprescribing/.venv38/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/webapps/openprescribing/.venv38/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/send_monthly_alerts.py", line 259, in handle
    error_deferrer.try_email(
  File "/webapps/openprescribing/openprescribing/common/alert_utils.py", line 53, in __exit__
    raise exception
common.alert_utils.BatchedEmailErrors: Encountered 32 mail exceptions (showing last traceback only): `anymail.exceptions.AnymailRequestsAPIError: Mailgun API response 404 (Not Found): '404 page not found\n'`
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

**Comment by richiecroker** [comment]
@madwort having a tidy - was this resolved?
