### ISSUE TITLE
DMD import failure

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#549]
```
hello@openprescribing-with-volumn:/webapps/openprescribing/openprescribing$ python manage.py import_dmd --source_directory=/tmp/dmd/ --settings=openprescribing.settings.production
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/webapps/openprescribing/openprescribing/dmd/management/commands/import_dmd.py", line 347, in handle
    add_bnf_codes(options['source_directory'])
  File "/webapps/openprescribing/openprescribing/dmd/management/commands/import_dmd.py", line 224, in add_bnf_codes
    source_directory, "Converted_DRUG_SNOMED_BNF.xlsx"))
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/openpyxl/reader/excel.py", line 183, in load_workbook
    wb.active = read_workbook_settings(archive.read(ARC_WORKBOOK)) or 0
  File "/usr/lib/python2.7/zipfile.py", line 935, in read
    return self.open(name, "r", pwd).read()
  File "/usr/lib/python2.7/zipfile.py", line 961, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'xl/workbook.xml' in the archive"
```

**Comment by sebbacon** [comment]
Unable to reproduce this locally. Assume I had done something like rename an unzipped zip archive to the expected name.
