### ISSUE TITLE
Rationalise how code uses BigQuery

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#561]
We use both `googleapiclient` (old-style) and `google.cloud.bigquery` (new-style) libraries for talking to BQ.  There is also a lot of duplicated code throughout the codebase, as well as code that mixes interacting with BQ with other stuff (like transforming CSV files or downloading data from PG).

We should produce a single simple wrapper around `google.cloud.bigquery.client.Client` for talking to BQ, and write other functions for doing other things.

As a first step, we can bring the `ebmdatalab-python` library into the main repo.  (See #559.)  We can then migrate, task-by-task, to using the new wrapper.

**Comment by inglesp** [comment]
Here's an unfiltered dump of my notes about how we use BQ at the moment:

 * frontend.management.commands.create_views
    * bq is used a lot; I haven't unpicked this yeet
    * uses e.bq.get_bq_service
      * inserts and waits for jobs
        * could be done with g.c.bq
 * frontend.tests.commands.test_create_views
    * e.bq.load_prescribing_data_from_file
    * e.bq.load_ccgs_from_pg
    * e.bq.load_statistics_from_pg
 * frontend.management.commands.import_hscic_prescribing
    * bq only used when --reimport-all is passed to command
      * this is completely untested
      * will it ever be used again?
    * uses g.c.bq.dataset.Dataset
      * this is for a dataset called tmp_eu
    * uses e.bq.query_and_return
    * uses e.bq.bq.Client, which is actually g.c.bq.Client
    * uses e.bq.copy_table_to_gcs
    * uses e.bq.download_from_gcs
 * frontend.management.commands.import_measures
    * uses e.bq.query_and_return
      * there's some funky table-name-replacing code for testing
    * uses e.bq.get_rows
 * frontend.management.command.convert_hscic_prescribing
    * e.bq.copy_table_to_gcs
    * e.bq.download_from_gcs
    * e.bq.wait_for_job
    * g.c.bq.Client
      * client.run_sync_query
      * client.run_async_query
 * frontend.management.commands.generate_presentation_replacements
    * e.bq.load_data_from_file
    * e.bq.copy_table_to_gcs
    * e.bq.download_from_gcs
    * e.bq.wait_for_job
    * g.c.bq.Client
      * client.run_async_query
 * frontend.tests.commands.test_import_ppu_savings
    * e.bq.load_prescribing_data_from_file
 * frontend.tests.commands.test_import_measures
    * e.bq.load_prescribing_data_from_file
    * e.bq.load_data_from_file
 * pipeline.management.commands.bigquery_upload
    * e.bq.load_data_from_pg
    * e.bq.load_presentation_from_pg
    * e.bq.load_statistics_from_pg
    * e.bq.load_ccgs_from_pg
    * pipeline.cloud_utils.stuff
      * this also calls discovery.build, so could probably use get_bq_service
        * as well as inserting jobs, it lists tables
  * Smoketests
    * Does a synchronous query

**Comment by inglesp** [comment]
First problems: I'm sometimes seeing data that I've inserted into a table with the `g.c.bq` client not appearing, and I'm also seeing 503 errors when I try to insert data.

I've managed to create the following repro scenario:

```
# bq_test.py

from google.cloud import bigquery as gcbq


def bq_test(dataset_name, table_name):
    client = gcbq.Client(project='ebmdatalab')

    dataset = client.dataset(dataset_name)
    dataset.create()

    schema = [
        gcbq.SchemaField('a', 'INTEGER'),
        gcbq.SchemaField('b', 'STRING'),
    ]

    table = dataset.table(table_name, schema)
    table.create()

    table.insert_data([[1, 'Alice'], [2, 'Bob']])

    for row in table.fetch_data():
        print(row)

    table.delete()
    dataset.delete()
```

In the first case, if I create a dataset + table, then delete the dataset + table, then recreate the dataset + table, inserting data into the table succeeds, but the data cannot be retrieved:

```
>>> import bq_test
>>> bq_test.bq_test('testdataset1', 't1')
(1, u'Alice')
(2, u'Bob')
>>> bq_test.bq_test('testdataset1', 't1')
# crickets
```

Some time later (at least several minutes...) I am able to insert data into the table again.

In the second case, if I create a dataset + table, then delete the dataset + table, then recreate the dataset and create a table with a different name, inserting data into the table raises an exception:

```
>>> bq_test.bq_test('testdataset2', 't2a')
(1, u'Alice')
(2, u'Bob')
>>> bq_test.bq_test('testdataset2', 't2b')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bq_test.py", line 22, in bq_test
    table.insert_data([[1, 'Alice'], [2, 'Bob']])
  File "/Users/inglesp/.pyenv/versions/openprescribing/lib/python2.7/site-packages/google/cloud/bigquery/table.py", line 816, in insert_data
    data=data)
  File "/Users/inglesp/.pyenv/versions/openprescribing/lib/python2.7/site-packages/google/cloud/_http.py", line 293, in api_request
    raise exceptions.from_http_response(response)
google.cloud.exceptions.ServiceUnavailable: 503 POST https://www.googleapis.com/bigquery/v2/projects/ebmdatalab/datasets/testdataset2/tables/t2b/insertAll: Error encountered during execution. Retrying may solve the problem.
```

**Comment by inglesp** [comment]
In the second case, the library's behaving as it should.  For the first case, I've created an issue against the library.

In both cases, the solution is to not delete the dataset.

**Comment by inglesp** [comment]
No, even not deleting the dataset causes problems.

The reason I'm stumbling over this is that it's going to make testing fiddlier than it needs to be.
