### ISSUE TITLE
August alert mailouts failed

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#620]
This tends to happen every month, but usually only one or two mailouts are affected. Check how many were affected this month, then make improvements to code so we don't have to check so manually every time.

```
(.venv)hello@largeweb2:/webapps/openprescribing/openprescribing$ python manage.py send_monthly_alerts --settings=openprescribing.settings.production
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/send_monthly_alerts.py", line 161, in handle
    email_retrier.try_email(callback)
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/send_monthly_alerts.py", line 204, in __exit__
    self.exceptions[-1][2])
frontend.management.commands.send_monthly_alerts.BatchedEmailErrors: Encountered 4 mail exceptions (showing last traceback only): `CalledProcessError: Command '/usr/local/bin/phantomjs /webapps/openprescr
ibing/openprescribing/frontend/management/commands/grab_chart.js "https://openprescribing.net/ccg/11X/" /mnt/database/tmp/tmpHaHxE2.png "#lplidocaine" 1024x1024 1000' returned non-zero exit status 1, Call
edProcessError: Command '/usr/local/bin/phantomjs /webapps/openprescribing/openprescribing/frontend/management/commands/grab_chart.js "https://openprescribing.net/ccg/02Q/" /mnt/database/tmp/tmpGNRkh5.png
 "#lpglucosamine" 1024x1024 1000' returned non-zero exit status 1, CalledProcessError: Command '/usr/local/bin/phantomjs /webapps/openprescribing/openprescribing/frontend/management/commands/grab_chart.js
 "https://openprescribing.net/practice/J82187/" /mnt/database/tmp/tmpaxVCNN.png "#lprubefacients" 1024x1024 1000' returned non-zero exit status 1, CalledProcessError: Command '/usr/local/bin/phantomjs /we
bapps/openprescribing/openprescribing/frontend/management/commands/grab_chart.js "https://openprescribing.net/practice/B82023/" /mnt/database/tmp/tmpfi78SA.png "#lprubefacients" 1024x1024 1000' returned n
on-zero exit status 1`
```

**Comment by sebbacon** [comment]
Grr. Github lost my comments. Short version:

About 1 in 6 alerts are failing to be built. This represents a significant performance degradation on previous runs.

* [ ] Investigate performance degradation
* [ ] Write failures to a file (or database) and add a flag for the alert process to resend them

**Comment by sebbacon** [comment]
1. Performance

This New Relic analysis suggests a lot of time in the measure_global handler, including what looks like some N+1 queries (2k+ select calls per transaction)

![image](https://user-images.githubusercontent.com/211271/32328288-6315086e-bfd1-11e7-8b56-c624c03f93a6.png)

**Comment by sebbacon** [comment]
So the measure_global handler in the normal case should be very fast:

```sql
SELECT
  mg.month AS date,
  mg.numerator,
  mg.denominator,
  mg.measure_id,
  mg.calc_value,
  mg.percentiles,
  mg.cost_savings,
  ms.name,
  ms.title,
  ms.description,
  ms.why_it_matters,
  ms.tags_focus,
  ms.denominator_short,
  ms.numerator_short,
  ms.url,
  ms.is_cost_based,
  ms.is_percentage,
  ms.low_is_good
FROM
  frontend_measureglobal mg
JOIN
  frontend_measure ms
ON
  mg.measure_id=ms.id
  AND 'core' = ANY(ms.tags)
ORDER BY
  mg.measure_id,
  mg.month
```

```
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                QUERY PLAN                                                                │
├──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Sort  (cost=602.41..608.17 rows=2303 width=2142) (actual time=14.241..16.579 rows=2342 loops=1)                                          │
│   Sort Key: mg.measure_id, mg.month                                                                                                      │
│   Sort Method: quicksort  Memory: 4760kB                                                                                                 │
│   ->  Hash Join  (cost=16.70..473.80 rows=2303 width=2142) (actual time=0.194..5.008 rows=2342 loops=1)                                  │
│         Hash Cond: ((mg.measure_id)::text = (ms.id)::text)                                                                               │
│         ->  Seq Scan on frontend_measureglobal mg  (cost=0.00..421.23 rows=3423 width=1046) (actual time=0.009..1.668 rows=3422 loops=1) │
│         ->  Hash  (cost=16.24..16.24 rows=37 width=1107) (actual time=0.170..0.170 rows=37 loops=1)                                      │
│               Buckets: 1024  Batches: 1  Memory Usage: 39kB                                                                              │
│               ->  Seq Scan on frontend_measure ms  (cost=0.00..16.24 rows=37 width=1107) (actual time=0.012..0.106 rows=37 loops=1)      │
│                     Filter: ('core'::text = ANY ((tags)::text[]))                                                                        │
│                     Rows Removed by Filter: 18                                                                                           │
│ Planning time: 0.578 ms                                                                                                                  │
│ Execution time: 17.714 ms                                                                                                                │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
(Although I note that the SQL is wrong - the join shouldn't be ANDed)
