### ISSUE TITLE
Consider what to do about functional / selenium tests

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#642]
They are extremely flaky. It is very rare that the tests pass on all four browser targets.  This makes continuous integration impossible and makes it more likely we'll accidentally merge broken branches (because we get used to ignoring red Travis errors).

I've looked at this before and found the whole thing quite mysterious. We're executing the tests over a custom tunnel to a VM over which we have no control with very little debug output. 

Options:
* Look harder into the failures and consider how they might be fixed
* Look at using a different selenium test environment (e.g. browserstack)
* See if one of the targets succeeds more than the others, and focus on getting that one browser working flawlessly (i.e. better than nothing)
* Give up on browser-driven functional testing

Collecting examples of the failures below in case useful.

**Comment by sebbacon** [comment]
[`Bad Status Line`](https://travis-ci.org/ebmdatalab/openprescribing/jobs/302511055), which repeats, followed by an `Internal Server Error` and then `WebDriverException: Message: Invalid message: Due to a previous error, this job has already finished`

```
======================================================================
ERROR: test_ccg_measures_explore_link (frontend.tests.functional.test_general.GeneralFrontendTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/openprescribing/frontend/tests/functional/test_general.py", line 127, in test_ccg_measures_explore_link
    self.browser.get(url)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 254, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 464, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 526, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
```

**Comment by sebbacon** [comment]
[`StaleElementReferenceException: Message: Element is no longer attached to the DOM`](https://travis-ci.org/ebmdatalab/openprescribing/jobs/302511054) - a kind of timeout
