### ISSUE TITLE
nondeterministic bigquery failure: test_convert_hscic_prescribing

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#649]
This assert just got hit on Travis:

```
======================================================================
FAIL: test_data_is_aggregated (frontend.tests.commands.test_convert_hscic_prescribing.ConvertHscicPrescribingTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/openprescribing/frontend/tests/commands/test_convert_hscic_prescribing.py", line 47, in test_data_is_aggregated
    call_command('convert_hscic_prescribing', filename=raw_data_path)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/code/openprescribing/frontend/management/commands/convert_hscic_prescribing.py", line 68, in handle
    assert results.rows[0][0] == 0
AssertionError
----------------------------------------------------------------------
```

**Comment by inglesp** [comment]
This is the commit: https://github.com/ebmdatalab/openprescribing/commit/189acffeb9b8684d675e77d94a4435afae5a20a2.

**Comment by inglesp** [comment]
Closing this, as we haven't seen it since we started using a new dataset for each test run.
