### ISSUE TITLE
import_measures failed with 500 error for 2017_09

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#651]
The error's from BigQuery:

```
Traceback (most recent call last):                                                                                                                                                                            File "manage.py", line 12, in <module>                                                                                                                                                                        execute_from_command_line(sys.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/webapps/openprescribing/openprescribing/pipeline/management/commands/fetch_and_import.py", line 12, in handle
    run_all(kwargs['year'], kwargs['month'])
  File "/webapps/openprescribing/openprescribing/pipeline/runner.py", line 438, in run_all
    run_task(task, year, month, last_imported=last_imported)
  File "/webapps/openprescribing/openprescribing/pipeline/runner.py", line 403, in run_task
    task.run(year, month, **kwargs)
  File "/webapps/openprescribing/openprescribing/pipeline/runner.py", line 254, in run
    call_command(*tokens)
  File "/webapps/openprescribing/openprescribing/pipeline/runner.py", line 383, in call_command
    return django_call_command(*args)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/import_measures.py", line 95, in handle
    practice_rows_created = practice_calculation.calculate()
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/import_measures.py", line 534, in calculate
    number_rows_written = self.write_practice_ratios_to_database()
  File "/webapps/openprescribing/openprescribing/frontend/management/commands/import_measures.py", line 639, in write_practice_ratios_to_database
    for datum in self.get_rows_as_dicts(self.table_name()):
  File "/webapps/openprescribing/openprescribing/gcutils/bigquery.py", line 152, in get_rows_as_dicts
    for row in self.get_rows():
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/google/cloud/iterator.py", line 218, in _items_iter
    for page in self._page_iter(increment=False):
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/google/cloud/iterator.py", line 254, in _page_iter
    page = self._next_page()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/google/cloud/iterator.py", line 348, in _next_page
    response = self._get_next_page_response()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/google/cloud/iterator.py", line 399, in _get_next_page_response
    query_params=params)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/google/cloud/_http.py", line 293, in api_request
    raise exceptions.from_http_response(response)
google.cloud.exceptions.InternalServerError: 500 GET https://www.googleapis.com/bigquery/v2/projects/ebmdatalab/datasets/measures/tables/practice_data_ace/data?pageToken=BHDWKOW7L4AQAAASAUIIBAEAAUNAQCGF2INBBIENAYQP777777777777P4VAA%3D%3D%3D: An internal error occurred and the request could not be completed.
```

**Comment by inglesp** [comment]
Two questions:

 * what's failed (and was it our fault?)
 * what state is the system in now?

**Comment by inglesp** [comment]
Pretty sure this isn't our fault.

And nothing's been written to the database yet:

```
>>> MeasureValue.objects.filter(month='2017-09-01').count()
0
>>> MeasureGlobal.objects.filter(month='2017-09-01').count()
0
```

so it should be safe to re-run the pipeline.
