### ISSUE TITLE
Possible nondeterministic bigquery failure: codename "coconut"

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/openprescribing#661]
https://travis-ci.org/ebmdatalab/openprescribing/jobs/304759806

```
======================================================================
ERROR: test_data_is_aggregated (frontend.tests.commands.test_convert_hscic_prescribing.AggregateTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/code/openprescribing/frontend/tests/commands/test_convert_hscic_prescribing.py", line 81, in test_data_is_aggregated
    self.gcs_uri, target.name, date='2016_01_01')
  File "/code/openprescribing/frontend/management/commands/convert_hscic_prescribing.py", line 92, in aggregate_nhs_digital_data
    exporter.export_to_storage(print_header=False)
  File "/code/openprescribing/gcutils/bigquery.py", line 245, in export_to_storage
    wait_for_job(job)
  File "/code/openprescribing/gcutils/bigquery.py", line 296, in wait_for_job
    raise JobError(job.errors)
JobError: [{u'reason': u'internalError', u'message': u'An internal error occurred and the request could not be completed.'}]
======================================================================
FAIL: test_the_lot (gcutils.tests.test_bigquery.BQClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/openprescribing/gcutils/tests/test_bigquery.py", line 66, in test_the_lot
    self.assertEqual(sorted(results.rows), rows[2:])
AssertionError: Lists differ: [] != [(3, 'coconut')]
Second list contains 1 additional elements.
First extra element 0:
(3, 'coconut')
- []
+ [(3, 'coconut')]
```

**Comment by inglesp** [comment]
Closing this, as we haven't seen it since we started using a new dataset for each test run.
