### ISSUE TITLE
fetch_and_import_ncso_concessions is failing

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#730]
When run manually, we see:

```
(.venv)hello@largeweb2:/webapps/openprescribing/openprescribing$ python manage.py fetch_and_import_ncso_concessions --settings=openprescribing.settings.production
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/webapps/openprescribing/openprescribing/dmd/management/commands/fetch_and_import_ncso_concessions.py", line 37, in handle
    Client('dmd').upload_model(NCSOConcession)
  File "/webapps/openprescribing/openprescribing/gcutils/bigquery.py", line 201, in upload_model
    table.insert_rows_from_pg(model, columns, transformer)
  File "/webapps/openprescribing/openprescribing/gcutils/bigquery.py", line 268, in insert_rows_from_pg
    self.insert_rows_from_csv(f.name)
  File "/webapps/openprescribing/openprescribing/gcutils/bigquery.py", line 260, in insert_rows_from_csv
    wait_for_job(job)
  File "/webapps/openprescribing/openprescribing/gcutils/bigquery.py", line 382, in wait_for_job
    raise JobError(job.errors)
gcutils.bigquery.JobError: [{u'reason': u'invalid', u'message': u'Error while reading data, error message: CSV table encountered too many errors, giving up. Rows: 1; errors: 1.', u'location': u'mediaupload-snapshot'}, {u'reason': u'invalid', u'message': u"Error while reading data, error message: Could not parse '2017-11-01 00:00:00' as date for field date (position 1) starting at location 0", u'location': u'mediaupload-snapshot'}]
```

It's the uploading of data to BQ after the import that's the problem.  Should be a straightforward fix.

**Comment by inglesp** [comment]
The problem was that the `dmd.ncsoconcession` table already existed in the `ebmdatalab` project, and its `date` column had type `DATE`.  I'd changed the code so that we were uploading the `date` column with `TIMESTAMP` format, assuming that the column would have type `TIMESTAMP` (this is to allow for `JOIN`ing against other tables), but the upload was rejected because the format was wrong.  Deleting the table means that when the data is next uploaded, the table will be created with the correct columns.
