### ISSUE TITLE
Importing tariff data is failing

### ISSUE THREAD

**Issue by inglesp** [ebmdatalab/openprescribing#733]
```
$ python manage.py fetch_and_import_drug_tariff --settings=openprescribing.settings.production
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/webapps/openprescribing/openprescribing/dmd/management/commands/fetch_and_import_drug_tariff.py", line 64, in handle
    import_month(xls_file, date)
  File "/webapps/openprescribing/openprescribing/dmd/management/commands/fetch_and_import_drug_tariff.py", line 90, in import_month
    product_id=get_product_id(d['vmpp snomed code']),
  File "/webapps/openprescribing/openprescribing/dmd/management/commands/fetch_and_import_drug_tariff.py", line 113, in get_product_id
    vpid = DMDVmpp.objects.get(pk=vmpp).vpid
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/webapps/openprescribing/.venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
dmd.models.DoesNotExist: DMDVmpp matching query does not exist.
```

**Comment by inglesp** [comment]
The older version of `import_drug_tariff` would have ignored this, but would then have had fallen over when it tried to create a `TariffPrice` object with a null product.

Running the old code gives

```
django.db.utils.IntegrityError: null value in column "product_id" violates not-null constraint
DETAIL:  Failing row contains (670826, 2017-10-01, 2860, null, 3, 20985011000001108).
```

and printing the logged exception gives `Could not find VMPP with id 2.0985011e+16` (haha).

So either the dmd data is out of date (which it might well be -- see #732) or the drug tariff references a non-existent VMPP.

**Comment by inglesp** [comment]
Coming back to this, I have a horrid feeling about the representation of the ID...

I'm doing `print("Could not find VMPP with id %s" % vmpp)`, which would only print `2.0985011e+16` if `vmpp` was a float.  And looking at the spreadsheet of tariffs for January from https://www.nhsbsa.nhs.uk/pharmacies-gp-practices-and-appliance-contractors/drug-tariff/drug-tariff-part-viii/, there's nothing for VMPP ID 20985011000001108, but there is for 20985011000001109, and:

```
>>> float(20985011000001108) == float(20985011000001109)
True
```

**Comment by inglesp** [comment]
Tariff data is loaded from a spreadsheet into a dataframe with `pd.read_excel()`, and the problem is that sometimes there's an extra row between the headings and the data:

![image](https://user-images.githubusercontent.com/28734/35279605-71dec9d4-0045-11e8-8ee2-bc60470625cf.png)

and sometimes there's not:

![image](https://user-images.githubusercontent.com/28734/35279623-7a81cf6e-0045-11e8-8b83-fab96499749d.png)

When there is an extra row, Pandas thinks the `VMPP Snomed Code` must be a `NaN` for that row, and so sets the row's `dtype` to `float64`.

You can pass a `dtype` to `pd.read_excel()`, but that doesn't help us, as Pandas will do the conversion after it has loaded the data, and so we lose the precision.

Given that we're only using Pandas to load from Excel, I think the solution is to find something less clever to read from Excel.

**Comment by sebbacon** [comment]
Yuck :nauseated_face:
